### ISSUE TITLE
const exports = {} missing?

### ISSUE THREAD

**Issue by nmhub** [atti187/esmodules#1]
When I build my Apps Script project, the compiled file seems to not include `const exports = {}`, which causes an error in the Apps Script IDE. I think I'm following all the steps ok.

**Comment by atti187** [comment]
That's the whole point! It shouldn't include any exports-statements, as described in https://github.com/google/clasp/blob/master/docs/esmodules.md.

It's been a while since this example project was created, but I just copied the contents of /build/index.js into Code.gs in a new App Sheet project and it runs fine - see screenshot below.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/6089718/145191112-88e964fc-bb44-4e01-b4c2-d255d236dce8.png">

**Comment by nmhub** [comment]
Sorry - I had an export at the bottom of my index.ts :/ Thank you for the quick reply. This project is really useful
